### ISSUE TITLE
Can't enable plugin - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by fracz** [angular/batarang#200]
When trying to enable the plugin via "Enable" checkbox, my website stops working with the following error in the console.

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module ngHintModules due to:
RangeError: Maximum call stack size exceeded
    at Array.forEach (native)
    at module.exports (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1220:21)
    at module.exports (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1271:5)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1274:7
    at Array.forEach (native)
    at module.exports (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1272:21)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1274:7
    at Array.forEach (native)
    at module.exports (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1272:21)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1274:7
http://errors.angularjs.org/1.3.6/$injector/modulerr?p0=ngHintModules&p1=Ra…nsion%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A1274%3A7
```

**Comment by waratah** [comment]
Happens to me as well.   Similar to issue 157

**Comment by arecaps** [comment]
Same here

**Comment by dceddia** [comment]
I get the same thing. There's a question on SO about this too: http://stackoverflow.com/questions/27393367/chrome-extension-hint-js-nghintmodules

I tried reverting to 0.4.3 and it does seem to fix this problem.

**Comment by eseceve** [comment]
I get the same problem

**Comment by SomeKittens** [comment]
Can anyone get this to repro with a minimal app?

**Comment by gbrennon** [comment]
same here...

**Comment by Zeouterlimits** [comment]
Yeah, I am having the same issue.

Error:
Failed to instantiate module ngHintModules due to:
RangeError: Maximum call stack size exceeded
    at module.exports (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1441:26)

Chrome Version: 44.0.2403.125 (64-bit)
AngularJS Batarang: 0.8.5

**Comment by SomeKittens** [comment]
Posting another "Me too" won't help us find the issue.  If you're encountering this, please try to recreate it with a minimal app.

**Comment by sjurba** [comment]
This answer suggests it has something to do with module loading: http://stackoverflow.com/a/27399197

Perhaps something to look into?

**Comment by gary-b** [comment]
I spent a bit of time trying to repro this based on that answer, unfortunately without success..

**Comment by sjurba** [comment]
How about if you create a cyclic dependency? Or perhaps you simply need a large application with a large number of dependencies... 

Here is a current stacktrace from the latest batarang version:
````
Uncaught Error: [$injector:modulerr] Failed to instantiate module ngHintModules due to:
RangeError: Maximum call stack size exceeded
    at Array.forEach (native)
    at module.exports (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1455:21)
    at module.exports (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1506:5)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1509:7
    at Array.forEach (native)
    at module.exports (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1507:21)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1509:7
    at Array.forEach (native)
    at module.exports (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1507:21)
````

This points to this function (hint.js:1505):
````
var storeUsedModules = module.exports = function(module, modules){
  if(module) {
    storeDependencies(module);
    module.requires.forEach(function(modName) {
      var mod = modules[modName];
      storeUsedModules(mod, modules);
    });
  }
};
````

As you can see it is recurses through all modules and their dependencies. Looks like a good place to start. But it also seems this problem is within angular-hint?

**Comment by SomeKittens** [comment]
Having trouble reproducing this, but what @sjurba wrote very much makes sense.  Would be very easy to trigger an overflow there.

**Comment by SomeKittens** [comment]
Theoretical fix in above PR.

**Comment by sjurba** [comment]
If you can build a version of batarang for me, I can try to test it and see if the fix helped.

**Comment by SomeKittens** [comment]
(assuming you have `gulp` installed globally)

```bash
mkdir angular && cd angular
git clone git@github.com:angular/batarang.git
git clone git@github.com:angular/angular-hint.git
cd angular-hint
git checkout track-seen-modules && git pull origin track-seen-modules
npm i && gulp browserify
npm link
cd ../batarang
npm link angular-hint
npm i && gulp browserify
``

^ Should get you a Batarang repo pointed to the other branch of Angular hint.

Open Chrome Extensions, select `Load Unpacked Extension` browse to the directory you created above, pick `batarang`.  You'll probably see a load of warnings, ignore them.  Disable regular Batarang so there's no confusion/conflicts.

You should be running the dev version of Batarang in regular Chrome.

**Comment by sjurba** [comment]
Super. The fix worked. Also double checked by disabling the specific fix by removing: `seen.push(name);`, in which case the stack overflow is back.

**Comment by SomeKittens** [comment]
Fixed in c91ef9e4d8d32b9488b5c8c7bf9ce5aa78e1902a

**Comment by gary-b** [comment]
Great stuff SomeKittens and sjurba.

**Comment by bopm** [comment]
Why there is no release for that fix? It's still not working in 0.10.1 as there is still old angular-hint in it.

**Comment by debrice** [comment]
@bopm  Plugin was last Updated is October 1, 2015. The fix haven't been deployed yet to the google extension store.

**Comment by SomeKittens** [comment]
@debrice We're working on a release as I'm typing this.

**Comment by evanjmg** [comment]
Is this released yet?

**Comment by SomeKittens** [comment]
@evanjmg What version are you running?  0.10 or 0.4?  (Batarang "Stable" isn't affiliated with this project).

**Comment by evanjmg** [comment]
AngularJS Batarang 0.10.7 - developer mode - followed SomeKittens commands.

**Comment by tom94zoe** [comment]
+1
